version: 2
references:
  ## Workspaces
  workspace: &workspace
    ~/src

jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
        ## Cache
        gradle_key: &gradle_key
                      jars-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

    steps:
      - checkout
      - restore_cache:
          key: *gradle_key
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: *gradle_key
      - run:
          name: Build Debug
          command: ./gradlew assembleDebug
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-result





workflows:
  version: 2
  workflow:
    jobs:
      - test_unit
      - test_instrumentation:
          requires:
            - test_unit
